fieldLayouts:
  f198a667-ee5e-498d-a2ff-b04ea0b5437c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: df0ba3e5-f5f4-47a1-bcf2-f08fd173a89b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 755dfdc3-10ac-486c-be29-dea7bbecb180
        userCondition: null
fs: localFiles
handle: localFiles
name: 'Local Files'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
