defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  c1d05648-15bc-4c24-8069-b17513693b45: # Debug Vizy 181
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{{ (object.parent ? object.parent.uri ~ ''/'' : '''') }}{slug}'
structure:
  maxLevels: 3
  uid: 08dd0044-b305-4983-b706-a75374370869
type: structure
